### PR TITLE
Crow soft document branch

### PR DESCRIPTION
**Pull request by L00131535**

### CODE REVIEW

**Review by Bharathi03 — COMMENTED** [review]
team we can merge commit by commit into master in incremental way than merging aftre so many commits

**Review by Bharathi03 — APPROVED** [review]
Approving the merge to master

**Comment by L00086074** [comment]
Closing Pull Request as this is documentation and should not be included on the master.

**Comment by L00086074** [comment]
Please change to Documentation Branch
git checkout CrowSoft-Document-Branch		Checkout Branch
Check this location for git commands and update the document with anything you fell is useful.

https://github.com/rlennon/CrowSoft/blob/CrowSoft-Document-Branch/Documentation/Tools%20and%20Training/CrowSoft_GitHub_GIT_User_Guide.docx

**Pull request closed without merging**
